# Generated by Django 4.2.3 on 2023-11-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_message_author_remove_message_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
